import { precacheAndRoute } from 'workbox-precaching';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { registerRoute } from 'workbox-routing';
import { clientsClaim } from 'workbox-core';
import { openDB } from 'idb';

clientsClaim();
self.skipWaiting();

// Precache the app shell generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// API Caching: network first, fallback to cache for offline reads
registerRoute(
  ({ url }) => url.origin === 'https://script.google.com',
  new NetworkFirst({
    cacheName: 'gas-api-cache',
    networkTimeoutSeconds: 5,
    matchOptions: {
      ignoreSearch: true
    }
  })
);

// CDNs & Icons Caching (FontAwesome): cache first to instantly render offline!
registerRoute(
  ({ url }) => url.origin.includes('cdnjs.cloudflare.com') || url.origin.includes('fonts.googleapis.com'),
  new CacheFirst({
    cacheName: 'external-fonts-icons',
    plugins: [
      {
        cacheableResponse: { statuses: [0, 200] }
      }
    ]
  })
);

// Advanced Service Worker Native Sync Process
const executeNativeSync = async () => {
  try {
    const db = await openDB('homeschool_db', 1);
    const queue = await db.getAll('sync_queue');
    if (!queue || queue.length === 0) return;

    // Must match the API endpoints deployed
    const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbwrmGSQHclLHRtmh1p4m0oMutpxsgBYEw98DG0M-45WYIkWA6Xcf-ko10fih5M-INe6/exec';

    const bulkPayload = queue.map(q => ({ action: q.endpoint, args: q.payload, timestamp: q.timestamp }));

    const res = await fetch(SCRIPT_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain;charset=utf-8' },
      body: JSON.stringify({ action: 'syncOfflineQueue', args: [bulkPayload] })
    });

    if (!res.ok) {
      throw new Error(`GAS Request Failed with HTTP ${res.status}`);
    }

    const rawText = await res.text();
    let result;
    try {
      result = JSON.parse(rawText);
    } catch(e) {
      throw new Error("Received HTML error page from Google instead of JSON. Rate limit assumed.");
    }

    if (result.status === 'success') {
      await db.clear('sync_queue');
      // If client is secretly open, tell them to reload visual state!
      const clients = await self.clients.matchAll();
      clients.forEach(c => c.postMessage({ type: 'SYNC_COMPLETED', data: result.data }));
    } else {
      throw new Error(`GAS logical block: ${result.message}`);
    }
  } catch (err) {
    console.error("[SW] Native sync failed, maintaining queue", err);
    // Explicitly rethrow err so the Browser's Background Sync API natively reschedules for us with OS backoffs!
    throw err;
  }
};

// Listen to Sync Background API
self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-queue') {
    console.log('[Service Worker] Sync event triggered - Executing Native Flow');
    event.waitUntil(executeNativeSync());
  }
});
